# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-13 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=256)),
                ('page_url', models.CharField(max_length=1024)),
                ('url_text', models.CharField(max_length=512)),
                ('url_link', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'url_list',
            },
        ),
    ]
