# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url_List',
            fields=[
                ('pk_id', models.AutoField(db_column='pk_id', primary_key=True, serialize=False)),
                ('start_url', models.CharField(max_length=1024)),
                ('page_url', models.CharField(max_length=1024)),
                ('link', models.CharField(max_length=1024)),
                ('link_type', models.CharField(max_length=50)),
                ('url_category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'url_list',
            },
        ),
    ]
